{"name": "成功", "status": "broken", "statusDetails": {"message": "pymysql.err.InternalError: (1003, \"Transaction error, need to rollback.Unknown column 'fake123123test1231' in 'where clause'\")", "trace": "self = <utils.pysql.PyMySQL object at 0x0000000004910E10>\ntb = 'customer_third_wechat', key = 'wx_union_id', value = 'fake123123test1231'\n\n    def checkdbok(self,tb,key,value):\n    \n        sql=\"select count(*) from \"+ tb +\" where \"+key+ \"=\"+value\n    \n        try:\n            cursor = self.conn.cursor()\n>           cursor.execute(sql)\n\nutils\\pysql.py:54: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pymysql.cursors.Cursor object at 0x0000000004910668>\nquery = 'select count(*) from customer_third_wechat where wx_union_id=fake123123test1231'\nargs = None\n\n    def execute(self, query, args=None):\n        \"\"\"Execute a query\n    \n        :param str query: Query to execute.\n    \n        :param args: parameters used with query. (optional)\n        :type args: tuple, list or dict\n    \n        :return: Number of affected rows\n        :rtype: int\n    \n        If args is a list or tuple, %s can be used as a placeholder in the query.\n        If args is a dict, %(name)s can be used as a placeholder in the query.\n        \"\"\"\n        while self.nextset():\n            pass\n    \n        query = self.mogrify(query, args)\n    \n>       result = self._query(query)\n\nvenv\\lib\\site-packages\\pymysql\\cursors.py:170: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pymysql.cursors.Cursor object at 0x0000000004910668>\nq = 'select count(*) from customer_third_wechat where wx_union_id=fake123123test1231'\n\n    def _query(self, q):\n        conn = self._get_db()\n        self._last_executed = q\n        self._clear_result()\n>       conn.query(q)\n\nvenv\\lib\\site-packages\\pymysql\\cursors.py:328: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pymysql.connections.Connection object at 0x0000000004910748>\nsql = b'select count(*) from customer_third_wechat where wx_union_id=fake123123test1231'\nunbuffered = False\n\n    def query(self, sql, unbuffered=False):\n        # if DEBUG:\n        #     print(\"DEBUG: sending query:\", sql)\n        if isinstance(sql, text_type) and not (JYTHON or IRONPYTHON):\n            if PY2:\n                sql = sql.encode(self.encoding)\n            else:\n                sql = sql.encode(self.encoding, 'surrogateescape')\n        self._execute_command(COMMAND.COM_QUERY, sql)\n>       self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n\nvenv\\lib\\site-packages\\pymysql\\connections.py:517: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pymysql.connections.Connection object at 0x0000000004910748>\nunbuffered = False\n\n    def _read_query_result(self, unbuffered=False):\n        self._result = None\n        if unbuffered:\n            try:\n                result = MySQLResult(self)\n                result.init_unbuffered_query()\n            except:\n                result.unbuffered_active = False\n                result.connection = None\n                raise\n        else:\n            result = MySQLResult(self)\n>           result.read()\n\nvenv\\lib\\site-packages\\pymysql\\connections.py:732: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pymysql.connections.MySQLResult object at 0x0000000004910BA8>\n\n    def read(self):\n        try:\n>           first_packet = self.connection._read_packet()\n\nvenv\\lib\\site-packages\\pymysql\\connections.py:1075: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pymysql.connections.Connection object at 0x0000000004910748>\npacket_type = <class 'pymysql.protocol.MysqlPacket'>\n\n    def _read_packet(self, packet_type=MysqlPacket):\n        \"\"\"Read an entire \"mysql packet\" in its entirety from the network\n        and return a MysqlPacket type that represents the results.\n    \n        :raise OperationalError: If the connection to the MySQL server is lost.\n        :raise InternalError: If the packet sequence number is wrong.\n        \"\"\"\n        buff = b''\n        while True:\n            packet_header = self._read_bytes(4)\n            #if DEBUG: dump_packet(packet_header)\n    \n            btrl, btrh, packet_number = struct.unpack('<HBB', packet_header)\n            bytes_to_read = btrl + (btrh << 16)\n            if packet_number != self._next_seq_id:\n                self._force_close()\n                if packet_number == 0:\n                    # MariaDB sends error packet with seqno==0 when shutdown\n                    raise err.OperationalError(\n                        CR.CR_SERVER_LOST,\n                        \"Lost connection to MySQL server during query\")\n                raise err.InternalError(\n                    \"Packet sequence number wrong - got %d expected %d\"\n                    % (packet_number, self._next_seq_id))\n            self._next_seq_id = (self._next_seq_id + 1) % 256\n    \n            recv_data = self._read_bytes(bytes_to_read)\n            if DEBUG: dump_packet(recv_data)\n            buff += recv_data\n            # https://dev.mysql.com/doc/internals/en/sending-more-than-16mbyte.html\n            if bytes_to_read == 0xffffff:\n                continue\n            if bytes_to_read < MAX_PACKET_LEN:\n                break\n    \n        packet = packet_type(buff, self.encoding)\n>       packet.check_error()\n\nvenv\\lib\\site-packages\\pymysql\\connections.py:684: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pymysql.protocol.MysqlPacket object at 0x00000000049107F0>\n\n    def check_error(self):\n        if self.is_error_packet():\n            self.rewind()\n            self.advance(1)  # field_count == error (we already know that)\n            errno = self.read_uint16()\n            if DEBUG: print(\"errno =\", errno)\n>           err.raise_mysql_exception(self._data)\n\nvenv\\lib\\site-packages\\pymysql\\protocol.py:220: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ndata = b\"\\xffQ\\x04#HY000Unknown column 'fake123123test1231' in 'where clause'\"\n\n    def raise_mysql_exception(data):\n        errno = struct.unpack('<h', data[1:3])[0]\n        is_41 = data[3:4] == b\"#\"\n        if is_41:\n            # client protocol 4.1\n            errval = data[9:].decode('utf-8', 'replace')\n        else:\n            errval = data[3:].decode('utf-8', 'replace')\n        errorclass = error_map.get(errno, InternalError)\n>       raise errorclass(errno, errval)\nE       pymysql.err.InternalError: (1105, \"Unknown column 'fake123123test1231' in 'where clause'\")\n\nvenv\\lib\\site-packages\\pymysql\\err.py:109: InternalError\n\nDuring handling of the above exception, another exception occurred:\n\npyfixture = ({'appkey': 2200, 'custid': 50000382, 'ip_address': '192.168.100.200', 'open_id': 'fakeopenid201912247891122', ...}, ('0', '成功'))\n\n    @allure.title('{pyfixture[1][1]}')\n    @pytest.mark.weixin_bind_custid\n    @pytest.mark.flaky(reruns=1,reruns_delay=60)\n    def test_WeixinBindCustid(pyfixture):\n    \n        #请求\n        url=Weixin_Bind_Custid.url\n        data=pyfixture[0]\n        res=request(url=url,data=data)\n        #print(data)\n        assert res['statusCode']==pyfixture[1][0]\n    \n        if res['statusCode']==WeixinBindCustidReturnCodeEnum.SUCCESS.value[0]:\n>           assert PyMySQL().checkdbok('customer_third_wechat','wx_union_id',Weixin_Bind_Custid.initparams['union_id']),'''未写入数据库'''\n\ntestcase\\Weixin_Bind_Custid_test.py:126: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nutils\\pysql.py:58: in checkdbok\n    cursor.execute(sql)\nvenv\\lib\\site-packages\\pymysql\\cursors.py:170: in execute\n    result = self._query(query)\nvenv\\lib\\site-packages\\pymysql\\cursors.py:328: in _query\n    conn.query(q)\nvenv\\lib\\site-packages\\pymysql\\connections.py:517: in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\nvenv\\lib\\site-packages\\pymysql\\connections.py:732: in _read_query_result\n    result.read()\nvenv\\lib\\site-packages\\pymysql\\connections.py:1075: in read\n    first_packet = self.connection._read_packet()\nvenv\\lib\\site-packages\\pymysql\\connections.py:684: in _read_packet\n    packet.check_error()\nvenv\\lib\\site-packages\\pymysql\\protocol.py:220: in check_error\n    err.raise_mysql_exception(self._data)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ndata = b\"\\xff\\xeb\\x03#HY000Transaction error, need to rollback.Unknown column 'fake123123test1231' in 'where clause'\"\n\n    def raise_mysql_exception(data):\n        errno = struct.unpack('<h', data[1:3])[0]\n        is_41 = data[3:4] == b\"#\"\n        if is_41:\n            # client protocol 4.1\n            errval = data[9:].decode('utf-8', 'replace')\n        else:\n            errval = data[3:].decode('utf-8', 'replace')\n        errorclass = error_map.get(errno, InternalError)\n>       raise errorclass(errno, errval)\nE       pymysql.err.InternalError: (1003, \"Transaction error, need to rollback.Unknown column 'fake123123test1231' in 'where clause'\")\n\nvenv\\lib\\site-packages\\pymysql\\err.py:109: InternalError"}, "parameters": [{"name": "pyfixture", "value": "({'union_id': 'fake123123test1231', 'custid': 50000382, 'appkey': 2200, 'open_id': 'fakeopenid201912247891122', 'ip_address': '192.168.100.200', 'permanent_id': 1231231132131313, 'trace_id': 12312213122222222, 'source_url': 'http://www.testweb.com', 'result_format': 'json'}, ('0', '成功'))"}], "start": 1592976188957, "stop": 1592976189054, "uuid": "3757b89f-5789-4c07-b7d7-b8198750e2e7", "historyId": "317b27400ad51a0bb99f91d8b7ef6fe2", "testCaseId": "515bd0cba7b7bf3b9f0543a6caac3d78", "fullName": "testcase.Weixin_Bind_Custid_test#test_WeixinBindCustid", "labels": [{"name": "tag", "value": "weixin_bind_custid"}, {"name": "tag", "value": "flaky(reruns=1, reruns_delay=60)"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "Weixin_Bind_Custid_test"}, {"name": "host", "value": "A06P-A90F12DAA"}, {"name": "thread", "value": "4404-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.Weixin_Bind_Custid_test"}]}